### ISSUE TITLE
Incorrect alignment of the "About Me" section in the Discord theme

### ISSUE THREAD

**Issue by JuniorSuperTux** [stronk-dev/Tokyo-Night-Linux#15]
Can be observed by clicking on random user's profile. The following is an example
![image](https://user-images.githubusercontent.com/65844719/183345959-3fce3a13-e54b-47b8-a550-79e5d9f4b9f8.png)

**Comment by JuniorSuperTux** [comment]
Can be fixed by adding the following:

```css

.userInfoSection-3her-v .userInfoBody-1zgAd0{padding-left: 16px;}
.userInfoTitle-39qq0Y{padding-left: 16px;}
```
